license="All rights reserved"

modLoader="javafml"

loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

[[mods]] #mandatory

modId="recruits"

version="1.6.0"

displayName="Recriuts Mod"
updateJSONURL="https://github.com/talhanation/recruits/blob/main/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/recruits"

logoFile="logo.png"

credits="talhanation"

authors="talhanation"
# The description text for the mod (multi line!) (#mandatory)
description='''
This Mod adds hireable Villager Recruits with differnet Ranks like in M&B-Bannerlord into Minecraft.
'''
